version: '3'

services:
  defort_flask:
    build: ./flask_app
    expose:
      - 5000
    ports:
      - "5000:5000"
    hostname: defort_flask
    domainname: defort_flask.com
    environment:
      - FLASK_APP=app.py

  nginx:
    build: .
    ports:
      - "1337:80"
    depends_on:
      - defort_flask
    environment:
      APP_HOST: defort_flask
      NGINX_HOST: foobar.com
      NGINX_PORT: 80